spring.application.name=APP_NAME
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/DBNAME
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=secretkey
jwt.expiration=timeinms