spring.application.name=APP_NAME
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/DBNAME
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/
app.rabbitmq.exchange=booking.events
app.rabbitmq.queues.email=email.notifications
app.rabbitmq.routing-keys.confirmed=booking.confirmed
app.rabbitmq.routing-keys.cancelled=booking.cancelled

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=user@gmail.com
spring.mail.password=app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

jwt.secret=secretkey
jwt.expiration=timeinms